# DB設定
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/osaifu
quarkus.datasource.username=osaifu
quarkus.datasource.password=osaifu
quarkus.datasource.devservices.enabled=false
quarkus.hibernate-orm.database.generation=update
# Token関連
smallrye.jwt.sign.key.location=classpath:keys/rsaPrivateKey.pem
mp.jwt.verify.publickey.location=classpath:keys/rsaPublicKey.pem
mp.jwt.verify.issuer=https://osaifuplus.tvq.jpe